import java.util.ArrayList;
import java.util.List;

public class Solution {
    public int uniqueXorTriplets(int[] nums) {
        // Step 1: Identify all unique values present in the input array
        boolean[] present = new boolean[1501];
        List<Integer> uniqueNums = new ArrayList<>();
        for (int num : nums) {
            if (!present[num]) {
                present[num] = true;
                uniqueNums.add(num);
            }
        }
        
        // Step 2: Mark all possible XOR values generated by pairs (x XOR y)
        // Since max value is 1500, max XOR value will be less than 2048
        boolean[] hasPairXOR = new boolean[2048];
        int n = uniqueNums.size();
        for (int i = 0; i < n; i++) {
            for (int j = i; j < n; j++) {
                int xorPair = uniqueNums.get(i) ^ uniqueNums.get(j);
                hasPairXOR[xorPair] = true;
            }
        }
        
        // Step 3: Check which values from 0 to 2047 can form a triplet
        int uniqueTripletCount = 0;
        for (int v = 0; v < 2048; v++) {
            for (int z : uniqueNums) {
                // If (v XOR z) forms a valid pair XOR, then v is a valid triplet XOR
                if (hasPairXOR[v ^ z]) {
                    uniqueTripletCount++;
                    break; // Move to the next potential triplet value
                }
            }
        }
        
        return uniqueTripletCount;
    }
}